app.security.users[0].username=joao
app.security.users[0].password=4321
app.security.users[0].role=USER

app.security.users[1].username=admin
app.security.users[1].password=1234
app.security.users[1].role=ADMIN

spring.application.name=Exemplo_Arquitetura_Completa
spring.datasource.url=jdbc:postgresql://localhost:5432/authenticator
spring.datasource.username=aramuni
spring.datasource.password=aramuni
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update