# Nome e porta da aplicacao
spring.application.name=taskflow
server.port=8080
 
# Banco de dados H2 em memoria (dados resetam a cada restart - ideal p/ estudo)
spring.datasource.url=jdbc:h2:mem:taskflowdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
 
# Console web do H2, acessivel em /h2-console (usuario: sa, senha vazia)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
 
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
 
# Thymeleaf - desabilita cache em dev para refletir mudancas no HTML na hora
spring.thymeleaf.cache=false
 
# Evita que o NAVEGADOR guarde em cache o CSS/JS antigo durante o desenvolvimento
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true