spring.application.name=SecureLoginPUC
app.user.username=joaopauloaramuni@gmail.com
app.user.password=4321
app.user.name=Joao
app.admin.username=admin
app.admin.password=1234
app.admin.name=Administrador
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=joaopauloaramuni@gmail.com
# https://myaccount.google.com/apppasswords
# sua senha de app aqui (É necessário ativar a autenticação de dois fatores antes no Gmail)
spring.mail.password=hzpjaczvuyuwnjmt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true