spring.application.name=SecureLoginPUC

# =========================================================
# USUÁRIO
# =========================================================

app.user.username=joaopauloaramuni@gmail.com
app.user.password=4321
app.user.name=Joao


# =========================================================
# ADMINISTRADOR
# =========================================================

app.admin.username=admin
app.admin.password=1234
app.admin.name=Administrador


# =========================================================
# GMAIL
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=joaopauloaramuni@gmail.com
spring.mail.password=SUA_NOVA_SENHA_DE_APP

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# =========================================================
# GOOGLE reCAPTCHA
# =========================================================

recaptcha.site-key=6LeEwsItAAAAAB4wX5NCt_c72PDo2Vpvds0BOO5Y
recaptcha.secret-key=6LeEwsItAAAAAKbWz-EEfZn1BxfoanhCeMPTvB_e