# fly.toml app configuration file generated for
# fly-io-view-restapi on 2024-01-29T00:02:00-03:00
# See https://fly.io/docs/reference/configuration/
# for information about how to use this file.

app = 'fly-io-view-restapi'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
